apiVersion: apps/v1
kind: Deployment
metadata:
  name: datg
spec:
  selector:
    matchLabels:
      app: datg
  template:
    metadata:
      labels:
        app: datg
    spec:
      containers:
      - image: pskreter/datg:v0.0.1-alpha
        name: datg
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
